# Generated by Django 6.0.4 on 2026-04-24 03:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ingredient name')),
                ('default_unit', models.CharField(choices=[('KG', 'Kilogram'), ('L', 'Liter'), ('PCS', 'Piece')], db_index=True, default='KG', max_length=5, verbose_name='default stock unit')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('remaining_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remaining stock')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='minimum stock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.ingredient', verbose_name='ingredient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'ingredient inventory',
                'verbose_name_plural': 'ingredient inventories',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='Bawang Goreng', max_length=150, verbose_name='product name')),
                ('variant_name', models.CharField(db_index=True, max_length=100, verbose_name='bawang goreng type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['variant_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(max_length=100, verbose_name='packaging label')),
                ('net_mass_grams', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='net mass (grams)')),
                ('remaining_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='remaining stock')),
                ('base_price_idr', models.PositiveBigIntegerField(help_text='Base purchase price in Rupiah, without decimals.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='base price (IDR)')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_variants', to='inventory.product', verbose_name='product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'product packaging',
                'verbose_name_plural': 'product packaging',
                'ordering': ['product__name', 'net_mass_grams', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['default_unit', 'is_active'], name='inventory_i_default_358730_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['created_by'], name='inventory_i_created_503224_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['updated_by'], name='inventory_i_updated_a3714f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['created_at'], name='inventory_i_created_b24282_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientinventory',
            index=models.Index(fields=['created_by'], name='inventory_i_created_202c59_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientinventory',
            index=models.Index(fields=['updated_by'], name='inventory_i_updated_e32417_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientinventory',
            index=models.Index(fields=['remaining_stock'], name='inventory_i_remaini_cda349_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientinventory',
            index=models.Index(fields=['minimum_stock'], name='inventory_i_minimum_60f0eb_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientinventory',
            index=models.Index(fields=['created_at'], name='inventory_i_created_89b331_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['variant_name', 'is_active'], name='inventory_p_variant_5cc692_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_by'], name='inventory_p_created_00cd94_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated_by'], name='inventory_p_updated_6de10d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='inventory_p_created_081871_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'variant_name'), name='uq_product_name_variant'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['product', 'is_active'], name='inventory_p_product_3a578f_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['created_by'], name='inventory_p_created_29f070_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['updated_by'], name='inventory_p_updated_f8dab2_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['remaining_stock'], name='inventory_p_remaini_83c3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['base_price_idr'], name='inventory_p_base_pr_5ca31d_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['net_mass_grams'], name='inventory_p_net_mas_ca4bae_idx'),
        ),
        migrations.AddIndex(
            model_name='productpackaging',
            index=models.Index(fields=['created_at'], name='inventory_p_created_b9fa44_idx'),
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(fields=('product', 'label'), name='uq_product_packaging_label_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productpackaging',
            constraint=models.UniqueConstraint(fields=('product', 'net_mass_grams'), name='uq_product_packaging_mass_per_product'),
        ),
    ]
