# Generated by Django 6.0.4 on 2026-04-24 03:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('production_date', models.DateField(db_index=True, verbose_name='production date')),
                ('shift_label', models.CharField(blank=True, max_length=50, verbose_name='shift label')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'production batch',
                'verbose_name_plural': 'production batches',
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionIngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity used')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usages', to='inventory.productionbatch', verbose_name='batch')),
                ('ingredient_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='inventory.ingredientinventory', verbose_name='ingredient inventory')),
            ],
            options={
                'verbose_name': 'production ingredient usage',
                'verbose_name_plural': 'production ingredient usages',
            },
        ),
        migrations.CreateModel(
            name='ProductionPackagingOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity produced')),
                ('bonus_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='bonus quantity')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_outputs', to='inventory.productionbatch', verbose_name='batch')),
                ('product_packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_outputs', to='inventory.productpackaging', verbose_name='product packaging')),
            ],
            options={
                'verbose_name': 'production packaging output',
                'verbose_name_plural': 'production packaging outputs',
            },
        ),
        migrations.CreateModel(
            name='ProductStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], db_index=True, max_length=3, verbose_name='movement type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity')),
                ('bonus_quantity', models.DecimalField(decimal_places=3, default=0, help_text='Extra package quantity produced as bonus.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='bonus quantity')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('movement_at', models.DateTimeField(db_index=True, verbose_name='movement at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('product_packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.productpackaging', verbose_name='product packaging')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'product stock movement',
                'verbose_name_plural': 'product stock movements',
                'ordering': ['-movement_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], db_index=True, max_length=3, verbose_name='movement type')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('movement_at', models.DateTimeField(db_index=True, verbose_name='movement at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('ingredient_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.ingredientinventory', verbose_name='ingredient inventory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'ingredient stock movement',
                'verbose_name_plural': 'ingredient stock movements',
                'ordering': ['-movement_at', '-id'],
                'indexes': [models.Index(fields=['ingredient_inventory', 'movement_type'], name='inventory_i_ingredi_a6f4f0_idx'), models.Index(fields=['created_by'], name='inventory_i_created_52cd0e_idx'), models.Index(fields=['updated_by'], name='inventory_i_updated_593af4_idx'), models.Index(fields=['movement_at'], name='inventory_i_movemen_7d33f3_idx'), models.Index(fields=['created_at'], name='inventory_i_created_54e866_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['production_date'], name='inventory_p_product_38168f_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['created_by'], name='inventory_p_created_88d157_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['updated_by'], name='inventory_p_updated_c64aba_idx'),
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['created_at'], name='inventory_p_created_a96f57_idx'),
        ),
        migrations.AddIndex(
            model_name='productioningredientusage',
            index=models.Index(fields=['batch', 'ingredient_inventory'], name='inventory_p_batch_i_a03135_idx'),
        ),
        migrations.AddConstraint(
            model_name='productioningredientusage',
            constraint=models.UniqueConstraint(fields=('batch', 'ingredient_inventory'), name='uq_batch_ingredient_usage'),
        ),
        migrations.AddIndex(
            model_name='productionpackagingoutput',
            index=models.Index(fields=['batch', 'product_packaging'], name='inventory_p_batch_i_629a65_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionpackagingoutput',
            constraint=models.UniqueConstraint(fields=('batch', 'product_packaging'), name='uq_batch_product_packaging_output'),
        ),
        migrations.AddIndex(
            model_name='productstockmovement',
            index=models.Index(fields=['product_packaging', 'movement_type'], name='inventory_p_product_f2a183_idx'),
        ),
        migrations.AddIndex(
            model_name='productstockmovement',
            index=models.Index(fields=['created_by'], name='inventory_p_created_853c18_idx'),
        ),
        migrations.AddIndex(
            model_name='productstockmovement',
            index=models.Index(fields=['updated_by'], name='inventory_p_updated_363163_idx'),
        ),
        migrations.AddIndex(
            model_name='productstockmovement',
            index=models.Index(fields=['movement_at'], name='inventory_p_movemen_d61730_idx'),
        ),
        migrations.AddIndex(
            model_name='productstockmovement',
            index=models.Index(fields=['created_at'], name='inventory_p_created_327e9c_idx'),
        ),
    ]
