# Generated by Django 6.0.4 on 2026-04-24 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productionbatch_productioningredientusage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackaging',
            name='list_price_idr',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Default selling price in Rupiah; used when no customer special price is set.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='list selling price (IDR)'),
        ),
    ]
