# Generated by Django 6.0.4 on 2026-05-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productpackaging_net_mass_kg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpackaging',
            options={'ordering': ['product__name', 'net_mass_kg', 'label'], 'verbose_name': 'product packaging', 'verbose_name_plural': 'product packaging'},
        ),
        migrations.RemoveIndex(
            model_name='productpackaging',
            name='inventory_p_remaini_83c3e9_idx',
        ),
        migrations.RenameIndex(
            model_name='productpackaging',
            new_name='inventory_p_net_mas_bbbb81_idx',
            old_name='inv_pp_net_mass_kg_idx',
        ),
    ]
