# Generated by Django 6.0.4 on 2026-05-06 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productstockmovement_mass_grams'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productstockmovement',
            new_name='inventory_p_product_5a76b5_idx',
            old_name='inventory_p_product_e3_idx',
        ),
        migrations.AlterField(
            model_name='productstockmovement',
            name='product_packaging',
            field=models.ForeignKey(blank=True, help_text='Optional SKU context (production, sales lines); null for manual mass-only entries.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.productpackaging', verbose_name='product packaging'),
        ),
    ]
