# Generated by Django 6.0.4 on 2026-05-08 03:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_inventory_p_product_e3_idx_inventory_p_product_5a76b5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='productioningredientusage',
            name='quantity_used',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity used'),
        ),
        migrations.AlterField(
            model_name='productionpackagingoutput',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity produced'),
        ),
    ]
