# Generated by Django 6.0.4 on 2026-07-13 08:33

from decimal import ROUND_HALF_UP, Decimal

import django.core.validators
from django.db import migrations, models


def backfill_price_per_kg(apps, schema_editor):
    """Derive Product.price_per_kg_idr from existing packaging prices.

    Uses list price (falling back to base price) divided by net mass of the
    packaging with the largest net mass, giving a stable per-kg figure.
    """
    Product = apps.get_model("inventory", "Product")
    ProductPackaging = apps.get_model("inventory", "ProductPackaging")

    for product in Product.objects.all():
        best = None  # (net_mass_kg, price_idr)
        for pkg in ProductPackaging.objects.filter(product=product):
            price = pkg.list_price_idr or pkg.base_price_idr
            net = pkg.net_mass_kg
            if not price or not net or net <= 0:
                continue
            if best is None or net > best[0]:
                best = (net, price)
        if best is None:
            continue
        per_kg = (Decimal(best[1]) / Decimal(best[0])).quantize(
            Decimal("1"), rounding=ROUND_HALF_UP
        )
        product.price_per_kg_idr = int(per_kg)
        product.save(update_fields=["price_per_kg_idr"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ingredientstockmovement_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productpackaging',
            name='inventory_p_base_pr_5ca31d_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_kg_idr',
            field=models.PositiveBigIntegerField(db_index=True, default=0, help_text='Fixed price per kilogram in Rupiah (set by admin). Each kemasan total is derived from this × net mass (kg).', validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per kg (IDR)'),
        ),
        migrations.RunPython(backfill_price_per_kg, noop),
        migrations.RemoveField(
            model_name='productpackaging',
            name='base_price_idr',
        ),
        migrations.RemoveField(
            model_name='productpackaging',
            name='list_price_idr',
        ),
    ]
