# Generated by Django 6.0.4 on 2026-07-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_productpackaging_inventory_p_base_pr_5ca31d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinventory',
            name='avg_cost_idr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Perpetual moving-average purchase cost per stock unit (kg/L/pcs). Updated on each verified purchase; used to value production consumption.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average cost (IDR)'),
        ),
        migrations.AddField(
            model_name='ingredientstockmovement',
            name='unit_cost_idr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit applied at this movement (audit): purchase price on IN, moving-average cost consumed on OUT. Null for legacy/manual rows.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit cost (IDR)'),
        ),
        migrations.AddField(
            model_name='product',
            name='avg_cost_per_kg_idr',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Perpetual moving-average production cost per kg (material only). Updated when finished mass is added by a production batch; used as COGS basis on sale.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average cost per kg (IDR)'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='material_cost_idr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total ingredient (material) cost consumed by this batch, valued at moving-average ingredient cost when the batch was recorded.', max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='material cost (IDR)'),
        ),
        migrations.AddField(
            model_name='productstockmovement',
            name='unit_cost_per_kg_idr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Production cost per kg at this movement (audit): batch cost on IN, moving-average cost on OUT (sale). Null for legacy/manual rows.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unit cost per kg (IDR)'),
        ),
    ]
