# Generated by Django 6.0.4 on 2026-07-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_ingredientinventory_avg_cost_idr_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productpackaging',
            name='uq_product_packaging_mass_per_product',
        ),
    ]
