# Generated by Django 6.0.4 on 2026-07-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_product_packaging_mass_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackaging',
            name='packaging_type',
            field=models.CharField(choices=[('KTK', 'Kotak'), ('BAL', 'Bal')], db_index=True, default='BAL', max_length=5, verbose_name='packaging type'),
        ),
    ]
