# Generated by Django 6.0.4 on 2026-05-08 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _backfill_badges(apps, schema_editor) -> None:
    EmployeeProfile = apps.get_model("account", "EmployeeProfile")
    StaffAttendanceBadge = apps.get_model("attendance", "StaffAttendanceBadge")
    for row in EmployeeProfile.objects.all().only("user_id"):
        StaffAttendanceBadge.objects.get_or_create(user_id=row.user_id)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_backfill_employee_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendanceBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_badge', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
            ],
            options={
                'verbose_name': 'staff attendance badge',
                'verbose_name_plural': 'staff attendance badges',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, verbose_name='work date')),
                ('checked_in_at', models.DateTimeField(verbose_name='checked in at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_daily_checkins', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'attendance daily check-in',
                'verbose_name_plural': 'attendance daily check-ins',
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date'), name='uniq_attendance_checkin_employee_work_date')],
            },
        ),
        migrations.RunPython(
            code=_backfill_badges,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
