# Generated by Django 6.0.4 on 2026-07-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_policy_fields'),
        ('payroll', '0003_weekly_saturday_payroll_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedailycheckin',
            name='paid_in_period',
            field=models.ForeignKey(blank=True, help_text='Diisi saat periode gaji difinalisasi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_paid', to='payroll.payrollperiod', verbose_name='paid in period'),
        ),
    ]
