# Generated by Django 6.0.4 on 2026-04-24 04:38

import django.core.validators
import django.db.models.deletion
import expenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('entry_kind', models.CharField(choices=[('INCOME', 'Pemasukan'), ('EXPENSE', 'Pengeluaran')], db_index=True, max_length=10, verbose_name='entry kind')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'operational category',
                'verbose_name_plural': 'operational categories',
                'ordering': ['entry_kind', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalCashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('direction', models.CharField(choices=[('INCOME', 'Pemasukan'), ('EXPENSE', 'Pengeluaran')], db_index=True, max_length=10, verbose_name='direction')),
                ('amount_idr', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount (IDR)')),
                ('occurred_on', models.DateField(db_index=True, verbose_name='occurred on')),
                ('description', models.TextField(verbose_name='description')),
                ('reference', models.CharField(blank=True, help_text='Optional reference, e.g. invoice number or PO code.', max_length=120, verbose_name='external reference')),
                ('attachment', models.FileField(blank=True, max_length=500, null=True, upload_to=expenses.models._attachment_upload_to, verbose_name='attachment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='expenses.operationalcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'operational cash entry',
                'verbose_name_plural': 'operational cash entries',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='operationalcategory',
            index=models.Index(fields=['entry_kind', 'is_active'], name='expenses_op_entry_k_4e70c4_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcategory',
            index=models.Index(fields=['created_at'], name='expenses_op_created_ab1016_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcashentry',
            index=models.Index(fields=['occurred_on', 'direction'], name='expenses_op_occurre_326b68_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcashentry',
            index=models.Index(fields=['category', 'occurred_on'], name='expenses_op_categor_45aff2_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcashentry',
            index=models.Index(fields=['created_by'], name='expenses_op_created_52fd30_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcashentry',
            index=models.Index(fields=['created_at'], name='expenses_op_created_aa35a7_idx'),
        ),
    ]
