# Generated by Django 6.0.4 on 2026-04-24 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalcashentry',
            name='purchase_in_order',
            field=models.ForeignKey(blank=True, help_text='Optional link when this line relates to ingredient procurement (pengeluaran).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_cash_entries', to='purchase.purchaseinorder', verbose_name='linked purchase in order'),
        ),
        migrations.AddField(
            model_name='operationalcashentry',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Optional link when this line relates to a customer sale (pemasukan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_cash_entries', to='purchase.salesorder', verbose_name='linked sales order'),
        ),
        migrations.AddIndex(
            model_name='operationalcashentry',
            index=models.Index(fields=['sales_order'], name='expenses_op_sales_o_c30941_idx'),
        ),
        migrations.AddIndex(
            model_name='operationalcashentry',
            index=models.Index(fields=['purchase_in_order'], name='expenses_op_purchas_7a3994_idx'),
        ),
        migrations.AddConstraint(
            model_name='operationalcashentry',
            constraint=models.CheckConstraint(condition=models.Q(('sales_order__isnull', True), ('purchase_in_order__isnull', True), _connector='OR'), name='expenses_entry_at_most_one_order_link'),
        ),
    ]
