# Generated by Django 6.0.4 on 2026-07-06 08:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_ingredientstockmovement_quantity_and_more'),
        ('payroll', '0003_weekly_saturday_payroll_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollperiod',
            options={'ordering': ['-pay_date'], 'verbose_name': 'payroll period', 'verbose_name_plural': 'payroll periods'},
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='daily_rate_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gaji per hari hadir (untuk pay_type DAILY).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='daily rate (IDR)'),
        ),
        migrations.AddField(
            model_name='employeecompensation',
            name='pay_type',
            field=models.CharField(choices=[('DAILY', 'Daily wage (attendance)'), ('PIECE_RATE', 'Piece rate (kupas)')], db_index=True, default='DAILY', max_length=16, verbose_name='pay type'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='advance_deduction_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Pinjaman (PINJAM).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='advance deduction (IDR)'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='bonus_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tambahan (TBH).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='bonus (IDR)'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='daily_rate_snapshot_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='daily rate snapshot (IDR)'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='gross_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='gross (IDR)'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='pay_type_snapshot',
            field=models.CharField(choices=[('DAILY', 'Daily wage (attendance)'), ('PIECE_RATE', 'Piece rate (kupas)')], default='DAILY', max_length=16, verbose_name='pay type snapshot'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='total_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total kg (kupas)'),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='monthly_base_salary_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Referensi opsional; tidak dipakai untuk hitung gaji harian.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monthly base salary (IDR)'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='base_salary_snapshot_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Referensi gaji pokok bulanan saat generate.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='base salary snapshot (IDR)'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='deductions_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Potongan telat / lainnya.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='deductions (IDR)'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='pay_date',
            field=models.DateField(db_index=True, verbose_name='pay date'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_end_date',
            field=models.DateField(verbose_name='period end (cutoff)'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='period_start_date',
            field=models.DateField(verbose_name='period start'),
        ),
        migrations.CreateModel(
            name='KupasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('rate_per_kg_idr', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='rate per kg (IDR)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resulting_ingredient', models.ForeignKey(blank=True, help_text='Bahan hasil kupas yang masuk stok (opsional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kupas_items', to='inventory.ingredient', verbose_name='resulting ingredient')),
            ],
            options={
                'verbose_name': 'kupas item',
                'verbose_name_plural': 'kupas items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KupasProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, verbose_name='work date')),
                ('kg', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='kg')),
                ('rate_snapshot_idr', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Diisi saat periode difinalisasi.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='rate snapshot (IDR)')),
                ('amount_idr', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='kg × tarif; diisi saat generate/finalize.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount (IDR)')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kupas_production_records', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('kupas_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='payroll.kupasitem', verbose_name='kupas item')),
                ('paid_in_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kupas_records_paid', to='payroll.payrollperiod', verbose_name='paid in period')),
            ],
            options={
                'verbose_name': 'kupas production record',
                'verbose_name_plural': 'kupas production records',
                'ordering': ['-work_date', 'employee__full_name'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='payroll_kup_employe_37fc69_idx'), models.Index(fields=['paid_in_period'], name='payroll_kup_paid_in_915641_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'kupas_item'), name='uniq_kupas_record_employee_date_item')],
            },
        ),
    ]
