# Generated by Django 6.0.4 on 2026-07-06 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_payrollperiod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kupasproductionrecord',
            options={'ordering': ['-work_date', 'employee__full_name', 'id'], 'verbose_name': 'kupas production record', 'verbose_name_plural': 'kupas production records'},
        ),
        migrations.RemoveConstraint(
            model_name='kupasproductionrecord',
            name='uniq_kupas_record_employee_date_item',
        ),
        migrations.AddIndex(
            model_name='kupasproductionrecord',
            index=models.Index(fields=['employee', 'work_date', 'kupas_item'], name='payroll_kup_employe_e46163_idx'),
        ),
    ]
