# Generated by Django 6.0.4 on 2026-08-27 02:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollentry_paid_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompensation',
            name='daily_rate_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Gaji per hari hadir (DAILY; dipakai jika gaji pokok bulanan kosong).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='daily rate (IDR)'),
        ),
        migrations.AlterField(
            model_name='employeecompensation',
            name='monthly_base_salary_idr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Jika diisi (>0) dan cadence MONTHLY + DAILY: dipakai sebagai gaji pokok. Jika kosong: hitung dari tarif harian × hadir. Tidak dipakai untuk PIECE_RATE.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='monthly base salary (IDR)'),
        ),
    ]
