# Generated by Django 6.0.4 on 2026-04-24 04:21

import django.core.validators
import django.db.models.deletion
import purchase.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_productpackaging_list_price_idr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='customer name')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='company name')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='NPWP / tax id')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('selling_price_idr', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='selling price (IDR)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='purchase.customer', verbose_name='customer')),
                ('product_packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='inventory.productpackaging', verbose_name='product packaging')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'customer product price',
                'verbose_name_plural': 'customer product prices',
                'ordering': ['customer__name', 'product_packaging__label'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='order code')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='supplier name')),
                ('supplier_phone', models.CharField(blank=True, max_length=50, verbose_name='supplier phone')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAYMENT_PROOF_UPLOADED', 'Payment proof uploaded'), ('VERIFIED', 'Verified by owner'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32, verbose_name='status')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='invoice number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='invoice date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('subtotal_idr', models.PositiveBigIntegerField(default=0, verbose_name='subtotal (IDR)')),
                ('tax_amount_idr', models.PositiveBigIntegerField(default=0, verbose_name='tax (IDR)')),
                ('total_idr', models.PositiveBigIntegerField(default=0, verbose_name='total (IDR)')),
                ('payment_proof', models.FileField(blank=True, max_length=500, null=True, upload_to=purchase.models._upload_payment_proof_path, verbose_name='payment proof (bukti TF)')),
                ('payment_proof_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='payment proof uploaded at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_purchase_in_orders', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'purchase in order',
                'verbose_name_plural': 'purchase in orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity')),
                ('unit_cost_idr', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='unit cost (IDR)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('ingredient_inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_in_lines', to='inventory.ingredientinventory', verbose_name='ingredient inventory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchaseinorder', verbose_name='order')),
            ],
            options={
                'verbose_name': 'purchase in line',
                'verbose_name_plural': 'purchase in lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order_code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='order code')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAYMENT_PROOF_UPLOADED', 'Payment proof uploaded'), ('VERIFIED', 'Verified by owner'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=32, verbose_name='status')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='invoice number')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='invoice date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('subtotal_idr', models.PositiveBigIntegerField(default=0, verbose_name='subtotal (IDR)')),
                ('tax_amount_idr', models.PositiveBigIntegerField(default=0, verbose_name='tax (IDR)')),
                ('total_idr', models.PositiveBigIntegerField(default=0, verbose_name='total (IDR)')),
                ('payment_proof', models.FileField(blank=True, max_length=500, null=True, upload_to=purchase.models._upload_payment_proof_path, verbose_name='payment proof (bukti TF)')),
                ('payment_proof_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='payment proof uploaded at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='purchase.customer', verbose_name='customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='verified by')),
            ],
            options={
                'verbose_name': 'sales order',
                'verbose_name_plural': 'sales orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='quantity')),
                ('unit_price_idr', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='unit price (IDR)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.salesorder', verbose_name='order')),
                ('product_packaging', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventory.productpackaging', verbose_name='product packaging')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'sales order line',
                'verbose_name_plural': 'sales order lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'name'], name='purchase_cu_is_acti_9d641f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='purchase_cu_created_f4490b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerproductprice',
            index=models.Index(fields=['customer', 'is_active'], name='purchase_cu_custome_e2e92b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerproductprice',
            index=models.Index(fields=['product_packaging', 'is_active'], name='purchase_cu_product_814b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='customerproductprice',
            index=models.Index(fields=['created_at'], name='purchase_cu_created_6eb161_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerproductprice',
            constraint=models.UniqueConstraint(fields=('customer', 'product_packaging'), name='uq_customer_product_packaging_price'),
        ),
        migrations.AddIndex(
            model_name='purchaseinorder',
            index=models.Index(fields=['status', 'created_at'], name='purchase_pu_status_11c67c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinorder',
            index=models.Index(fields=['supplier_name'], name='purchase_pu_supplie_4b11e4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinorder',
            index=models.Index(fields=['created_by'], name='purchase_pu_created_ac3ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinline',
            index=models.Index(fields=['order', 'ingredient_inventory'], name='purchase_pu_order_i_211929_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'created_at'], name='purchase_sa_status_c811a0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['customer', 'status'], name='purchase_sa_custome_87dbba_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['created_by'], name='purchase_sa_created_4cd5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorderline',
            index=models.Index(fields=['order', 'product_packaging'], name='purchase_sa_order_i_f72d55_idx'),
        ),
    ]
