# Generated by Django 6.0.4 on 2026-05-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_salesorder_default_awaiting_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Menunggu pembayaran'), ('PAYMENT_PROOF_UPLOADED', 'Sudah bayar'), ('VERIFIED', 'Pembayaran diterima'), ('CANCELLED', 'Dibatalkan')], db_index=True, default='AWAITING_PAYMENT', max_length=32, verbose_name='status'),
        ),
    ]
