# Generated by Django 6.0.4 on 2026-05-05 15:24

import purchase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_salesorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='invoice_date',
            field=models.DateField(blank=True, default=purchase.models._invoice_date_h_plus_one, null=True, verbose_name='invoice date'),
        ),
    ]
