# Generated by Django 6.0.4 on 2026-05-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_alter_salesorder_invoice_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseinorder',
            name='purchase_pu_supplie_4b11e4_idx',
        ),
        migrations.AlterField(
            model_name='purchaseinorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAYMENT_PROOF_UPLOADED', 'Payment proof uploaded'), ('VERIFIED', 'Verified by owner'), ('CANCELLED', 'Cancelled')], db_index=True, default='AWAITING_PAYMENT', max_length=32, verbose_name='status'),
        ),
        migrations.RemoveField(
            model_name='purchaseinorder',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='purchaseinorder',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='purchaseinorder',
            name='supplier_phone',
        ),
        migrations.RemoveField(
            model_name='purchaseinorder',
            name='tax_amount_idr',
        ),
    ]
