# Generated by Django 6.0.4 on 2026-05-06 03:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_remove_purchaseinorder_purchase_pu_supplie_4b11e4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantity'),
        ),
    ]
