# Generated by Django 6.0.4 on 2026-05-08 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0007_alter_purchaseinline_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wilayah",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True, verbose_name="updated at")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True, verbose_name="region name")),
                ("is_active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "region",
                "verbose_name_plural": "regions",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="wilayah",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="purchase.wilayah",
                verbose_name="region",
            ),
        ),
        migrations.AddIndex(
            model_name="wilayah",
            index=models.Index(fields=["is_active", "name"], name="purchase_wil_is_acti_4d85cb_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["wilayah", "name"], name="purchase_cus_wilayah_aed4d5_idx"),
        ),
    ]
