# Generated by Django 6.0.4 on 2026-05-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_wilayah_and_customer_region'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='purchase_cu_wilayah_48a6da_idx',
            old_name='purchase_cus_wilayah_aed4d5_idx',
        ),
        migrations.RenameIndex(
            model_name='wilayah',
            new_name='purchase_wi_is_acti_1ee1c1_idx',
            old_name='purchase_wil_is_acti_4d85cb_idx',
        ),
        migrations.AlterField(
            model_name='wilayah',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='wilayah',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
