# Generated by Django 6.0.4 on 2026-07-13 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_rename_purchase_cus_wilayah_aed4d5_idx_purchase_cu_wilayah_48a6da_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='cogs_material_idr',
            field=models.PositiveBigIntegerField(blank=True, help_text="Snapshot of material cost of goods sold for this line, valued at the product's moving-average cost when the order was verified. Null until verified.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='material COGS (IDR)'),
        ),
    ]
