# Generated by Django 6.0.4 on 2026-08-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_sales_purchase_verified_at_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchaseinorder',
            new_name='purchase_pu_status_c79ff7_idx',
            old_name='purchase_pu_status_verified_idx',
        ),
        migrations.RenameIndex(
            model_name='salesorder',
            new_name='purchase_sa_status_5f9231_idx',
            old_name='purchase_sa_status_verified_idx',
        ),
    ]
